### ISSUE TITLE
Zira bot naar Mira de kat

### ISSUE THREAD

**Issue by jonasclaes** [friendshipbubble/discord-bot#5]
De bericht opties die we zouden willen hebben waarmee gekozen kan worden voor bepaalde rollen zijn: 

1:
Kies hier je voornaamwoorden.
🟦 Hij/Hem
🟥 Zij/Haar
🟩 Hen/Hun
🟨 Die/Diens

Als je voornaamwoorden mist laat het dan aan een Dev weten, dan voegen wij deze toe. 

2:
Prive berichten preferenties
❤️ Vraag om toestemming
💚 Geen prive berichten
💜 Toegestaan - Algemeen
🧡 Toegestaan - Heftige dingen/ TW
🤍 Toegestaan - Groep gerelateerde berichten

3:
Kies je identiteit(en)
:asexual: Aseksueel
:pansexual: Panseksueel
:bisexual: Biseksueel
:homosexual: Homoseksueel
:transgender: transgender 
:intersex: interseks
🤍 Heteroseksueel
:nonbinary: nonbinary
:genderfluid: genderfluid 
:lesbian: lesbisch
🤎 CIS
💜 Queer
💛 Demi seksueel 
🖤 Questioning 

Als je identiteiten mist laat het dan aan een Dev weten, dan voegen wij deze toe. 

4: 
Relatiestatus:
🫂 In een relatie
👤 Single
👪 Non-monogaam - Niet op zoek
💋 Non-monogaam - Op zoek
🧑‍🤝‍🧑 Monogaam - Niet op zoek
👄 Monogaam - Op zoek

5: 
Privé kanalen
:homosexual: LGBTQIA+
⚕️ Spoonie
☮️ Mental Health
🔮 Witchy vibes
🪢  Kink en BDSM (de rol wordt weergegeven als "Spicy" zodat het voor vanilla's minder duidelijk is dat je hierin zit)
🧙‍♀️  Dungeons and dragons 
🐺  Weerwolven van Wakkerdam (bewerkt)

Door op de icoontjes te klikken, word je toegevoegd aan deze privé kanalen. Let op, er komt dan te staan dat jij in die kanalen zit. Mocht je graag in deze kanalen willen zonder dat andere mensen dat kunnen zien, stuur dan even een berichtje naar een Mod

6: 
Wil je een melding krijgen wanneer mensen uit de groep iets aan het ondernemen zijn, bijvoorbeeld wanneer ze gaan bellen, spelletjes gaan spelen of wanneer er iets georganiseerd wordt, klik dan de notificatie squad rol aan

 📢  Notificatie Squad

Verder hebben we ook een notificatie optie voor als je berichtjes wil krijgen wanneer er iets georganiseerd wordt over Minecraft of Kolonisten van Catan. Wil je daar meldingen van ontvangen, klik dan ook op onderstaande icoontjes. 

🟩 Minecraft squad
🟨 Catan squad

**Comment by jonasclaes** [comment]
TODO:
- [ ] Generalized function for defining these options
- [ ] Voornaamwoorden
- [ ] Prive berichten preferenties
- [ ] Identiteiten
- [ ] Relatiestatus
- [ ] Privekanalen
- [ ] Meldingen

**Comment by laurigiepmans** [comment]
Edit voor categorie 3:
Alle pride flags die we nog niet hadden, zijn nu toegevoegd aan emoji's, dus die kunnen hierbij gebruikt worden.


Kies je identiteit(en)
:asexual: Aseksueel
:pansexual: Panseksueel
:bisexual: Biseksueel
:homosexual: Homoseksueel
:transgender: transgender
:intersex: interseks
:heterosexual: Heteroseksueel
:nonbinary: nonbinary
:genderfluid: genderfluid
:lesbian: lesbisch
:cisgender: CIS
:queer: Queer
:demisexual: Demi seksueel
:questioning" Questioning
